### ISSUE TITLE
Got NullPointerException for dslink-java-opc-0.2.20.SNAPSHOT link

### ISSUE THREAD

**Issue by deepakjaju** [IOT-DSA/dslink-java-opc#7]
[2018-08-10 10:36:34.464434] 2018-08-10 10:36:34.464 [nioEventLoopGroup-2-12] INFO org.jinterop.dcom.core.JISession - for IID: 0002e000-0000-0000-c000-000000000046
[2018-08-10 10:36:34.464485] 2018-08-10 10:36:34.464 [nioEventLoopGroup-2-12] INFO org.jinterop.dcom.core.JIComObjectImpl - addRef: Adding 5 references for 0000f006-5578-4f30-bbb3-dc520e14ad4a session: 663004253
[2018-08-10 10:36:34.469146] 2018-08-10 10:36:34.468 [nioEventLoopGroup-2-12] ERROR org.dsa.iot.dslink.connection.connector.WebSocketConnector - 
[2018-08-10 10:36:34.469157] java.lang.NullPointerException
[2018-08-10 10:36:34.469160] 	at opc.OpcServer.init(OpcServer.java:60)
[2018-08-10 10:36:34.469163] 	at opc.OpcServer.restoreLastSession(OpcServer.java:252)
[2018-08-10 10:36:34.469166] 	at opc.ComServer.restoreLastSession(ComServer.java:806)
[2018-08-10 10:36:34.469168] 	at opc.OpcConn.restoreLastSession(OpcConn.java:198)
[2018-08-10 10:36:34.469171] 	at opc.OpcLink.restoreLastSession(OpcLink.java:72)
[2018-08-10 10:36:34.469174] 	at opc.OpcLink.init(OpcLink.java:41)
[2018-08-10 10:36:34.469176] 	at opc.OpcLink.start(OpcLink.java:37)
[2018-08-10 10:36:34.469178] 	at opc.Main.onResponderConnected(Main.java:37)
[2018-08-10 10:36:34.469181] 	at org.dsa.iot.dslink.DSLinkProvider$1$2$1.handle(DSLinkProvider.java:131)
[2018-08-10 10:36:34.469184] 	at org.dsa.iot.dslink.DSLinkProvider$1$2$1.handle(DSLinkProvider.java:128)
[2018-08-10 10:36:34.469186] 	at org.dsa.iot.dslink.connection.ConnectionManager$Client.connected(ConnectionManager.java:257)
[2018-08-10 10:36:34.469189] 	at org.dsa.iot.dslink.connection.ConnectionManager$1$2.handle(ConnectionManager.java:104)
[2018-08-10 10:36:34.469191] 	at org.dsa.iot.dslink.connection.ConnectionManager$1$2.handle(ConnectionManager.java:98)
[2018-08-10 10:36:34.469194] 	at org.dsa.iot.dslink.connection.connector.WebSocketConnector$WsHandler.onConnected(WebSocketConnector.java:142)
[2018-08-10 10:36:34.469197] 	at org.dsa.iot.dslink.provider.netty.DefaultWsProvider$WebSocketHandler.channelRead0(DefaultWsProvider.java:122)
[2018-08-10 10:36:34.469200] 	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
[2018-08-10 10:36:34.469203] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
[2018-08-10 10:36:34.469206] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
[2018-08-10 10:36:34.469208] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
[2018-08-10 10:36:34.469211] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[2018-08-10 10:36:34.469213] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
[2018-08-10 10:36:34.469216] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
[2018-08-10 10:36:34.469219] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
[2018-08-10 10:36:34.469221] 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
[2018-08-10 10:36:34.469224] 	at io.netty.handler.codec.http.websocketx.extensions.WebSocketClientExtensionHandler.channelRead(WebSocketClientExtensionHandler.java:128)
[2018-08-10 10:36:34.469227] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
[2018-08-10 10:36:34.469230] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
[2018-08-10 10:36:34.469232] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
[2018-08-10 10:36:34.469235] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[2018-08-10 10:36:34.469237] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
[2018-08-10 10:36:34.469241] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
[2018-08-10 10:36:34.469243] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
[2018-08-10 10:36:34.469246] 	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:428)
[2018-08-10 10:36:34.469248] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:288)
[2018-08-10 10:36:34.469251] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:262)
[2018-08-10 10:36:34.469254] 	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:243)
[2018-08-10 10:36:34.469256] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
[2018-08-10 10:36:34.469259] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
[2018-08-10 10:36:34.469276] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:327)
[2018-08-10 10:36:34.469284] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1336)
[2018-08-10 10:36:34.469287] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:349)
[2018-08-10 10:36:34.469290] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:335)
[2018-08-10 10:36:34.469292] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
[2018-08-10 10:36:34.469295] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
[2018-08-10 10:36:34.469297] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:544)
[2018-08-10 10:36:34.469300] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:485)
[2018-08-10 10:36:34.469303] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:399)
[2018-08-10 10:36:34.469306] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:371)
[2018-08-10 10:36:34.469308] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
[2018-08-10 10:36:34.469310] 	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
[2018-08-10 10:36:34.469313] 	at java.lang.Thread.run(Thread.java:748)
[2018-08-10 10:36:34.469316] 
[2018-08-10 10:36:34.470116] 2018-08-10 10:36:34.469 [nioEventLoopGroup-2-12] DEBUG io.netty.handler.codec.http.websocketx.WebSocket08FrameEncoder - Encoding WebSocket Frame opCode=1 length=4
[2018-08-10 10:36:34.470126] 2018-08-10 10:36:34.469 [nioEventLoopGroup-2-12] WARN org.dsa.iot.dslink.connection.ConnectionManager - WebSocket connection failed
[2018-08-10 10:36:34.470129] 2018-08-10 10:36:34.470 [nioEventLoopGroup-2-12] INFO org.dsa.iot.dslink.connection.ConnectionManager - Reconnecting in 1 seconds

**Comment by ilyatsarev** [comment]
@deepakjaju fixed in [dd0914e6b229b34b4a61544349e467ea3ce9250c](https://github.com/IOT-DSA/dslink-java-opc/commit/dd0914e6b229b34b4a61544349e467ea3ce9250c)
